name: auto_novel_reader_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # epub
  epubx:
    path: plugins/epubx-4.0.0
  image: ^3.3.0
  # 网络请求
  chopper: ^8.0.1+1
  dio: ^5.7.0
  http: ^1.2.2
  # html
  html: ^0.15.4
  flutter_widget_from_html: ^0.15.1
  # 文件选择
  path_provider: ^2.1.4
  file_picker: ^8.0.7
  file: ^7.0.0
  # 权限申请
  permission_handler: ^11.3.1
  # log 打印
  talker_flutter: ^4.2.0
  # 图标
  unicons: ^2.1.1
  # 吐司
  fluttertoast: ^8.2.8
  # 代码生成
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  # 状态管理
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
    # 动画
  animations: ^2.0.11
  flutter_staggered_animations: ^1.0.0
  # 持久化
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5
  # 网络图片
  cached_network_image: ^3.4.1
  # jwt
  dart_jsonwebtoken: ^2.14.0
  # url_launcher
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # 代码生成
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  chopper_generator: ^8.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/img/
